name: vcpianos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#384d5e'
    - '#b7b7b7'
    - '#737373'
    - '#1c1c1c'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
