name: vcpianos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#cfcac7'
    - '#fcfcfc'
    - '#a98a71'
    - '#885b3a'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
