name: vcpianos
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5698925
  brandStrength: 1
  lightness: 0.5107527
  brandColors:
    - '#010003'
    - '#FDFDFC'
    - '#5C425C'
    - '#A3887F'
    - '#77170D'
  rhythmicContrast: 0.5
typography_spectrum: 0.26976
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
