favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3125
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#ffffff'
    - '#384d5e'
    - '#b7b7b7'
    - '#737373'
    - '#1c1c1c'
  rhythmicContrast: 0.5
typography_spectrum: 0.26976
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: vcpianos
